Support TCP flags/seq/ack
pktgen/Pktgen-DPDK pull request #79
Opened 2021-08-11 14:29 UTC by snir

Signed-off-by: Stav Nir <stavnir@microsoft.com>

2021-08-11 15:46 UTC, pktgen requested changes
This is excellent work and thank you for submitting your patch.

I only had a few style comments and if you can update the style it look good to go.

2021-08-11 15:46 UTC, pktgen commented on app/pktgen-cmds.c
> +        }
For coding style I try not to have single line 'if', 'for', 'while', ... statements with {} around. Can you please remove the {} around these single lines.

2021-08-11 15:46 UTC, pktgen commented on app/pktgen-cmds.c
> +        return URG_FLAG;
Single line statements.

2021-08-11 15:46 UTC, pktgen commented on app/pktgen-cmds.c
> +    } else {
This one single line one too.

2021-08-11 15:46 UTC, pktgen commented on app/pktgen-cmds.c
> +    } else {
This one too

2021-08-12 08:57 UTC, snir commented
Thanks for the review, fixed it.

2021-08-12 13:01 UTC, merged